
spring:
  application:
    name: Health Care Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: hellcat
  jpa:
    hibernate:
      ddl-auto: update